<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="3"
           failures="3"
           errors="0"
           skipped="0"
           time="0.000">
  <properties />
            <testcase name="test_valid_mul_del" time="0.000" classname="Scenario_invoice.Scenario_del">
                <failure type="java.lang.RuntimeException"
                  message="java.io.FileNotFoundException: D:\akash\salenium\Reach_OAMC\Excel-files\03_Reachwell_masters_currency_Data.xls (The system cannot find the file specified)"
              >
<![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\akash\salenium\Reach_OAMC\Excel-files\03_Reachwell_masters_currency_Data.xls (The system cannot find the file specified)
  org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:161)
  org.testng.internal.Parameters.handleParameters(Parameters.java:429)
  org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
  org.testng.internal.Invoker.createParameters(Invoker.java:1075)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.io.FileNotFoundException: D:\akash\salenium\Reach_OAMC\Excel-files\03_Reachwell_masters_currency_Data.xls (The system cannot find the file specified)
  java.io.FileInputStream.open0(Native Method)
  java.io.FileInputStream.open(Unknown Source)
  java.io.FileInputStream.<init>(Unknown Source)
  java.io.FileInputStream.<init>(Unknown Source)
  Generic_component.ExcelReadWrite.<init>(ExcelReadWrite.java:20)
  Dataprovider_invoice.DataProvider_del.flagRowcount(DataProvider_del.java:42)
  Dataprovider_invoice.DataProvider_del.ValideditData(DataProvider_del.java:34)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:153)
  org.testng.internal.Parameters.handleParameters(Parameters.java:429)
  org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
  org.testng.internal.Invoker.createParameters(Invoker.java:1075)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
      </failure>

          </testcase>
            <testcase name="test_Invalid_delinvoice_blnk" time="0.000" classname="Scenario_invoice.Scenario_del">
                <failure type="java.lang.RuntimeException"
                  message="java.io.FileNotFoundException: D:\akash\salenium\Reach_OAMC\Excel-files\03_Reachwell_masters_currency_Data.xls (The system cannot find the file specified)"
              >
<![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\akash\salenium\Reach_OAMC\Excel-files\03_Reachwell_masters_currency_Data.xls (The system cannot find the file specified)
  org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:161)
  org.testng.internal.Parameters.handleParameters(Parameters.java:429)
  org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
  org.testng.internal.Invoker.createParameters(Invoker.java:1075)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.io.FileNotFoundException: D:\akash\salenium\Reach_OAMC\Excel-files\03_Reachwell_masters_currency_Data.xls (The system cannot find the file specified)
  java.io.FileInputStream.open0(Native Method)
  java.io.FileInputStream.open(Unknown Source)
  java.io.FileInputStream.<init>(Unknown Source)
  java.io.FileInputStream.<init>(Unknown Source)
  Generic_component.ExcelReadWrite.<init>(ExcelReadWrite.java:20)
  Dataprovider_invoice.DataProvider_del.flagRowcount(DataProvider_del.java:42)
  Dataprovider_invoice.DataProvider_del.Invalidedit_blnkData(DataProvider_del.java:17)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:153)
  org.testng.internal.Parameters.handleParameters(Parameters.java:429)
  org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
  org.testng.internal.Invoker.createParameters(Invoker.java:1075)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
      </failure>

          </testcase>
            <testcase name="test_valid_frstinvoice_del" time="0.000" classname="Scenario_invoice.Scenario_del">
                <failure type="java.lang.RuntimeException"
                  message="java.io.FileNotFoundException: D:\akash\salenium\Reach_OAMC\Excel-files\03_Reachwell_masters_currency_Data.xls (The system cannot find the file specified)"
              >
<![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\akash\salenium\Reach_OAMC\Excel-files\03_Reachwell_masters_currency_Data.xls (The system cannot find the file specified)
  org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:161)
  org.testng.internal.Parameters.handleParameters(Parameters.java:429)
  org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
  org.testng.internal.Invoker.createParameters(Invoker.java:1075)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.io.FileNotFoundException: D:\akash\salenium\Reach_OAMC\Excel-files\03_Reachwell_masters_currency_Data.xls (The system cannot find the file specified)
  java.io.FileInputStream.open0(Native Method)
  java.io.FileInputStream.open(Unknown Source)
  java.io.FileInputStream.<init>(Unknown Source)
  java.io.FileInputStream.<init>(Unknown Source)
  Generic_component.ExcelReadWrite.<init>(ExcelReadWrite.java:20)
  Dataprovider_invoice.DataProvider_del.flagRowcount(DataProvider_del.java:42)
  Dataprovider_invoice.DataProvider_del.Invalideditdata(DataProvider_del.java:25)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:153)
  org.testng.internal.Parameters.handleParameters(Parameters.java:429)
  org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
  org.testng.internal.Invoker.createParameters(Invoker.java:1075)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
