<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="9" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="109025" started-at="2016-02-02T10:23:14Z" finished-at="2016-02-02T10:25:03Z">
    <groups>
      <group name="invoice">
        <method signature="Scenario_create.test_Invalidcriti_blnk(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_create@6574b225]" name="test_Invalidcriti_blnk" class="Scenario_invoice.Scenario_create"/>
        <method signature="Scenario_create.test_Invalidinvoice(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_create@6574b225]" name="test_Invalidinvoice" class="Scenario_invoice.Scenario_create"/>
        <method signature="Scenario_create.test_Validcriti(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_create@6574b225]" name="test_Validcriti" class="Scenario_invoice.Scenario_create"/>
        <method signature="Scenario_del.test_Invalid_delinvoice_blnk(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_del@97e1986]" name="test_Invalid_delinvoice_blnk" class="Scenario_invoice.Scenario_del"/>
        <method signature="Scenario_del.test_valid_frstinvoice_del(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_del@97e1986]" name="test_valid_frstinvoice_del" class="Scenario_invoice.Scenario_del"/>
        <method signature="Scenario_del.test_valid_mul_del(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_del@97e1986]" name="test_valid_mul_del" class="Scenario_invoice.Scenario_del"/>
        <method signature="Scenario_edit.test_Invalidcriti(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_edit@2344fc66]" name="test_Invalidcriti" class="Scenario_invoice.Scenario_edit"/>
        <method signature="Scenario_edit.test_Invalidcriti_blnk(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_edit@2344fc66]" name="test_Invalidcriti_blnk" class="Scenario_invoice.Scenario_edit"/>
        <method signature="Scenario_edit.test_Validcriti(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_edit@2344fc66]" name="test_Validcriti" class="Scenario_invoice.Scenario_edit"/>
      </group> <!-- invoice -->
    </groups>
    <test name="Test" duration-ms="109025" started-at="2016-02-02T10:23:14Z" finished-at="2016-02-02T10:25:03Z">
      <class name="Scenario_invoice.Scenario_create">
        <test-method status="PASS" signature="test_Invalidcriti_blnk(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_create@6574b225]" name="test_Invalidcriti_blnk" duration-ms="20584" started-at="2016-02-02T15:53:15Z" data-provider="dp_Invalidinvoice_blnk" finished-at="2016-02-02T15:53:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[RW_19]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Part Payment]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Invoice Type Name can not be empty.]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Invalidcriti_blnk -->
        <test-method status="PASS" signature="test_Invalidinvoice(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_create@6574b225]" name="test_Invalidinvoice" duration-ms="18992" started-at="2016-02-02T15:53:36Z" data-provider="dp_Invalidinvoice" finished-at="2016-02-02T15:53:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[RW_20]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Full Payment]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Full Payment]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA['Full Payment'  Invoice Type Name already exists!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Invalidinvoice -->
        <test-method status="PASS" signature="test_Validcriti(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_create@6574b225]" name="test_Validcriti" duration-ms="27062" started-at="2016-02-02T15:53:56Z" data-provider="dp_Validinvoice" finished-at="2016-02-02T15:54:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[RW_21]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Part Payment]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Part Payment]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Part Payment]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Validcriti -->
      </class> <!-- Scenario_invoice.Scenario_create -->
      <class name="Scenario_invoice.Scenario_del">
        <test-method status="FAIL" signature="test_Invalid_delinvoice_blnk(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_del@97e1986]" name="test_Invalid_delinvoice_blnk" duration-ms="0" started-at="2016-02-02T15:55:03Z" data-provider="dp_Invaliddel_blnk" finished-at="2016-02-02T15:55:03Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:161)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:429)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
Caused by: java.lang.NullPointerException
	at Generic_component.ExcelReadWrite.Readvalue(Unknown Source)
	at Generic_component.ExcelReadWrite.Readvalue(Unknown Source)
	at Dataprovider_invoice.DataProvider_del.flagRowcount(Unknown Source)
	at Dataprovider_invoice.DataProvider_del.Invalidedit_blnkData(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:153)
	... 19 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Invalid_delinvoice_blnk -->
        <test-method status="FAIL" signature="test_valid_frstinvoice_del(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_del@97e1986]" name="test_valid_frstinvoice_del" duration-ms="0" started-at="2016-02-02T15:55:03Z" data-provider="dp_validdel" finished-at="2016-02-02T15:55:03Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:161)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:429)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
Caused by: java.lang.NullPointerException
	at Generic_component.ExcelReadWrite.Readvalue(Unknown Source)
	at Generic_component.ExcelReadWrite.Readvalue(Unknown Source)
	at Dataprovider_invoice.DataProvider_del.flagRowcount(Unknown Source)
	at Dataprovider_invoice.DataProvider_del.Invalideditdata(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:153)
	... 19 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_valid_frstinvoice_del -->
        <test-method status="FAIL" signature="test_valid_mul_del(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_del@97e1986]" name="test_valid_mul_del" duration-ms="0" started-at="2016-02-02T15:55:03Z" data-provider="dp_Valid_mul_del" finished-at="2016-02-02T15:55:03Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:161)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:429)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
Caused by: java.lang.NullPointerException
	at Generic_component.ExcelReadWrite.Readvalue(Unknown Source)
	at Generic_component.ExcelReadWrite.Readvalue(Unknown Source)
	at Dataprovider_invoice.DataProvider_del.flagRowcount(Unknown Source)
	at Dataprovider_invoice.DataProvider_del.ValideditData(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:153)
	... 19 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_valid_mul_del -->
      </class> <!-- Scenario_invoice.Scenario_del -->
      <class name="Scenario_invoice.Scenario_edit">
        <test-method status="FAIL" signature="test_Invalidcriti(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_edit@2344fc66]" name="test_Invalidcriti" duration-ms="10418" started-at="2016-02-02T15:54:23Z" data-provider="dp_Invalidcriti" finished-at="2016-02-02T15:54:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[RW_23]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Full Payment]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Full Payment]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA['Full Payment'  Invoice Name already exists!]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.interactions.MoveTargetOutOfBoundsException">
            <message>
              <![CDATA[Element cannot be scrolled into view:[object XrayWrapper [object HTMLSpanElement]]
Command duration or timeout: 30 milliseconds
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'DJ-PC', ip: '192.168.30.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=31.0, platform=WINDOWS, nativeEvents=true, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 2d83967f-cb5f-4529-9c34-4873b91ad40c]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.interactions.MoveTargetOutOfBoundsException: Element cannot be scrolled into view:[object XrayWrapper [object HTMLSpanElement]]
Command duration or timeout: 30 milliseconds
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'DJ-PC', ip: '192.168.30.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=31.0, platform=WINDOWS, nativeEvents=true, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 2d83967f-cb5f-4529-9c34-4873b91ad40c
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:50)
	at com.sun.proxy.$Proxy5.click(Unknown Source)
	at PageObject_invoice.Pageobject_edit.click_invoice(Unknown Source)
	at PageObject_invoice.Pageobject_edit.Commonprocessinvoice(Unknown Source)
	at Scenario_invoice.Scenario_edit.test_Invalidcriti(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
Caused by: org.openqa.selenium.interactions.MoveTargetOutOfBoundsException: Element cannot be scrolled into view:[object XrayWrapper [object HTMLSpanElement]]
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'DJ-PC', ip: '192.168.30.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: driver.version: unknown
	at <anonymous class>.WebElement.clickElement(file:///C:/Users/DJ/AppData/Local/Temp/anonymous2469378168449764249webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11036:7)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/DJ/AppData/Local/Temp/anonymous2469378168449764249webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11635:16)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///C:/Users/DJ/AppData/Local/Temp/anonymous2469378168449764249webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11640:7)
	at <anonymous class>.DelayedCommand.prototype.execute/<(file:///C:/Users/DJ/AppData/Local/Temp/anonymous2469378168449764249webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11582:5)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.interactions.MoveTargetOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Invalidcriti -->
        <test-method status="PASS" signature="test_Invalidcriti_blnk(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_edit@2344fc66]" name="test_Invalidcriti_blnk" duration-ms="17894" started-at="2016-02-02T15:54:34Z" data-provider="dp_Invalidcriti_blnk" finished-at="2016-02-02T15:54:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[RW_22]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Advance Payment]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Invoice Type Name can not be empty.]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Invalidcriti_blnk -->
        <test-method status="FAIL" signature="test_Validcriti(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Scenario_invoice.Scenario_edit@2344fc66]" name="test_Validcriti" duration-ms="10846" started-at="2016-02-02T15:54:52Z" data-provider="dp_Validcriti" finished-at="2016-02-02T15:55:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[RW_24]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Advance Payment]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Advance Payment]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Advance Payment]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.interactions.MoveTargetOutOfBoundsException">
            <message>
              <![CDATA[Element cannot be scrolled into view:[object XrayWrapper [object HTMLSpanElement]]
Command duration or timeout: 60 milliseconds
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'DJ-PC', ip: '192.168.30.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=31.0, platform=WINDOWS, nativeEvents=true, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 3741fd0b-96e3-4e17-bb4a-15e93a4811da]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.interactions.MoveTargetOutOfBoundsException: Element cannot be scrolled into view:[object XrayWrapper [object HTMLSpanElement]]
Command duration or timeout: 60 milliseconds
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'DJ-PC', ip: '192.168.30.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=31.0, platform=WINDOWS, nativeEvents=true, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 3741fd0b-96e3-4e17-bb4a-15e93a4811da
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:50)
	at com.sun.proxy.$Proxy5.click(Unknown Source)
	at PageObject_invoice.Pageobject_edit.click_invoice(Unknown Source)
	at PageObject_invoice.Pageobject_edit.Commonprocessinvoice(Unknown Source)
	at Scenario_invoice.Scenario_edit.test_Validcriti(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
Caused by: org.openqa.selenium.interactions.MoveTargetOutOfBoundsException: Element cannot be scrolled into view:[object XrayWrapper [object HTMLSpanElement]]
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'DJ-PC', ip: '192.168.30.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: driver.version: unknown
	at <anonymous class>.WebElement.clickElement(file:///C:/Users/DJ/AppData/Local/Temp/anonymous4252179031492529108webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11036:7)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/DJ/AppData/Local/Temp/anonymous4252179031492529108webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11635:16)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///C:/Users/DJ/AppData/Local/Temp/anonymous4252179031492529108webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11640:7)
	at <anonymous class>.DelayedCommand.prototype.execute/<(file:///C:/Users/DJ/AppData/Local/Temp/anonymous4252179031492529108webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11582:5)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.interactions.MoveTargetOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Validcriti -->
      </class> <!-- Scenario_invoice.Scenario_edit -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
